### ISSUE TITLE
bug(route): Fields such as host are not required

### ISSUE THREAD

**Issue by membphis** [iresty/apisix_dashboard#11]
![image](https://user-images.githubusercontent.com/6814606/62274474-8872b100-b472-11e9-81e2-55974b7e0ddd.png)

**Comment by juzhiyuan** [comment]
@membphis 

![image](https://user-images.githubusercontent.com/2106987/62296844-8d4f5900-b4a2-11e9-94c3-4eab8d6b524e.png)

API will response 400 error if I only post URI field.
