### ISSUE TITLE
optimize(service): style

### ISSUE THREAD

**Issue by membphis** [iresty/apisix_dashboard#13]
![image](https://user-images.githubusercontent.com/6814606/62275025-9c6ae280-b473-11e9-8a7e-7798756bae73.png)

please fix other similar points.

**Comment by juzhiyuan** [comment]
1. This value needs to be updated to which has no left-zero in server.
2. API is broken when id without left-zero.
http://39.97.63.215:9080/apisix/admin/upstreams/00000000000000003924

http://39.97.63.215:9080/apisix/admin/upstreams/3924
