### ISSUE TITLE
style: 操作栏按钮，需要固定宽度并右对齐

### ISSUE THREAD

**Issue by membphis** [iresty/apisix_dashboard#20]
![image](https://user-images.githubusercontent.com/6814606/62379161-fbfee600-b578-11e9-90f0-c514cfdb8494.png)

**Comment by juzhiyuan** [comment]
@moonming  由于 Upstream 表单中 Nodes 值嵌套多层数据，不方便将表格最外层边框去掉。其它列表页最外层边框已去除。
