### ISSUE TITLE
style: need a better style

### ISSUE THREAD

**Issue by membphis** [iresty/apisix_dashboard#22]
![image](https://user-images.githubusercontent.com/6814606/62379441-90694880-b579-11e9-93a4-9fc6a92d8d5d.png)

**Comment by juzhiyuan** [comment]
What style does the nodes value need?

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/62404629-2e83ff80-b5c8-11e9-9cbc-b0b8400cc971.png)

how about this?
