### ISSUE TITLE
插件配置页面，按钮状态问题

### ISSUE THREAD

**Issue by niktan** [iresty/apisix_dashboard#24]
![QQ图片20190808150130](https://user-images.githubusercontent.com/6444534/62681985-9930a300-b9ed-11e9-9788-50192c018c67.png)
这里如果没有select 只有 input的话 confirm一直是灰的无法点击

**Comment by juzhiyuan** [comment]
@niktan 收到，本周末修复。

**Comment by juzhiyuan** [comment]
@niktan 已修复，请更新本地 dashboard_built 仓库。
