### ISSUE TITLE
Feature Remove unused dependencies

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/apisix_dashboard#39]
@moonming @membphis  Do we need remove those unused dependencies? so that the Dashboard can be more slim but run faster.

**Comment by moonming** [comment]
sure, that will be great.

**Comment by juzhiyuan** [comment]
Ok, then I will process this this weekend.

**Comment by juzhiyuan** [comment]
@moonming I just removed some components & dependencies we don't need from master branch, and I have rebuilt the `apisix_dashboard_built` repo.

**Comment by juzhiyuan** [comment]
|Dependency|License|
|-------------|--------|
| fuse.js |	Apache-2.0 |
|echarts	| Apache-2.0|
|axios	|MIT|
|element-ui	|MIT|
|js-cookie	|MIT|
|normalize.css	|MIT|
|nprogress	|MIT|
|path-to-regexp	|MIT|
|register-service-worker	|MIT|
|screenfull	|MIT|
|uuid	|MIT|
|vue	|MIT|
|vue-class-component	|MIT|
|vue-count-to	|MIT|
|vue-i18n	|MIT|
|vue-property-decorator	|MIT|
|vue-router	|MIT|
|vue-svgicon	|MIT|
|vuex	|MIT|
|vuex-class	|MIT|
|vuex-module-decorators	|MIT|

**Comment by juzhiyuan** [comment]
|Dependency|License|
|-------------|--------|
| fuse.js |	Apache-2.0 |
|echarts	| Apache-2.0|
|axios	|MIT|
|element-ui	|MIT|
|js-cookie	|MIT|
|normalize.css	|MIT|
|nprogress	|MIT|
|path-to-regexp	|MIT|
|register-service-worker	|MIT|
|screenfull	|MIT|
|uuid	|MIT|
|vue	|MIT|
|vue-class-component	|MIT|
|vue-count-to	|MIT|
|vue-i18n	|MIT|
|vue-property-decorator	|MIT|
|vue-router	|MIT|
|vue-svgicon	|MIT|
|vuex	|MIT|
|vuex-class	|MIT|
|vuex-module-decorators	|MIT|
